query SEARCH_BY_DONOR_QUERY($filters: JSON) {
  file {
    aggregations(filters: $filters) {
      donors__donor_id {
        buckets {
          key
          doc_count
        }
      }
      donors__submitter_donor_id {
        buckets {
          key
          doc_count
        }
      }
    }
  }
}
