query SEARCH_BY_FILE_QUERY($filters: JSON) {
  file {
    hits(filters: $filters) {
      total
      edges {
        node {
          object_id
          file_id
          data_category
          study_id
        }
      }
    }
  }
}
