query SEARCH_BY_QUERY($filters: JSON) {
  file {
    hits(filters: $filters, first: 5) {
      total
      edges {
        node {
          file_id
          data_category
          study_id
        }
      }
    }
  }
}
