query SEARCH_BY_QUERY($filters: JSON) {
  file {
    hits(filters: $filters, first: 5) {
      total
      edges {
        node {
          object_id
          program_id: study_id
          file {
            name
          }
        }
      }
    }
  }
}
