// flow-typed signature: a5623b8e6aa397456745fe788ec1c000
// flow-typed version: <<STUB>>/babel-plugin-graphql-tag_v^2.1.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-graphql-tag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-graphql-tag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-graphql-tag/babel.config' {
  declare module.exports: any;
}

declare module 'babel-plugin-graphql-tag/dist/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-graphql-tag/jest.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-graphql-tag/babel.config.js' {
  declare module.exports: $Exports<'babel-plugin-graphql-tag/babel.config'>;
}
declare module 'babel-plugin-graphql-tag/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-graphql-tag/dist/index'>;
}
declare module 'babel-plugin-graphql-tag/jest.config.js' {
  declare module.exports: $Exports<'babel-plugin-graphql-tag/jest.config'>;
}
