// flow-typed signature: 2894a27820582871c39cf592a042fa68
// flow-typed version: <<STUB>>/babel-plugin-import-graphql_v^2.7.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-import-graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "babel-plugin-import-graphql" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "babel-plugin-import-graphql/build/constants" {
  declare module.exports: any;
}

declare module "babel-plugin-import-graphql/build/customImport" {
  declare module.exports: any;
}

declare module "babel-plugin-import-graphql/build/errorMessages" {
  declare module.exports: any;
}

declare module "babel-plugin-import-graphql/build/index" {
  declare module.exports: any;
}

declare module "babel-plugin-import-graphql/build/multiOp" {
  declare module.exports: any;
}

declare module "babel-plugin-import-graphql/build/requireGql" {
  declare module.exports: any;
}

// Filename aliases
declare module "babel-plugin-import-graphql/build/constants.js" {
  declare module.exports: $Exports<
    "babel-plugin-import-graphql/build/constants"
  >;
}
declare module "babel-plugin-import-graphql/build/customImport.js" {
  declare module.exports: $Exports<
    "babel-plugin-import-graphql/build/customImport"
  >;
}
declare module "babel-plugin-import-graphql/build/errorMessages.js" {
  declare module.exports: $Exports<
    "babel-plugin-import-graphql/build/errorMessages"
  >;
}
declare module "babel-plugin-import-graphql/build/index.js" {
  declare module.exports: $Exports<"babel-plugin-import-graphql/build/index">;
}
declare module "babel-plugin-import-graphql/build/multiOp.js" {
  declare module.exports: $Exports<"babel-plugin-import-graphql/build/multiOp">;
}
declare module "babel-plugin-import-graphql/build/requireGql.js" {
  declare module.exports: $Exports<
    "babel-plugin-import-graphql/build/requireGql"
  >;
}
