export default {
  hero: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '44px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  title: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '30px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  subtitle: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '22px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  subtitle2: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '18px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  navigation: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '15px',
    fontWeight: '600',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  paragraph: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '14px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.57',
    letterSpacing: 'normal',
  },
  data: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '12px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.17',
    letterSpacing: 'normal',
  },
  caption: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '11px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.27',
    letterSpacing: 'normal',
  },
};
