import { CSSProperties } from 'react';
export default {
  default: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: 'inherit',
    fontWeight: 'inherit',
    fontStyle: 'inherit',
    fontStretch: 'inherit',
    lineHeight: 'inherit',
    letterSpacing: 'inherit',
  } as CSSProperties,
  hero: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '40px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  } as CSSProperties,
  title: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '26px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  } as CSSProperties,
  subtitle: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '20px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  } as CSSProperties,
  subtitle2: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '16px',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  } as CSSProperties,
  sectionHeader: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '16px',
    fontWeight: 600,
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  } as CSSProperties,
  navigation: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '15px',
    fontWeight: 600,
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  } as CSSProperties,
  paragraph: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '14px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.57',
    letterSpacing: 'normal',
  } as CSSProperties,
  paragraph2: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '14px',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.71',
    letterSpacing: 'normal',
  } as CSSProperties,
  label: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '14px',
    fontWeight: 600,
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.57',
    letterSpacing: 'normal',
  } as CSSProperties,
  data: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '12px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.17',
    letterSpacing: 'normal',
  } as CSSProperties,
  caption: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '11px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.27',
    letterSpacing: 'normal',
  } as CSSProperties,
};
