
export default {
  default: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: 'inherit',
    fontWeight: 'inherit',
    fontStyle: 'inherit',
    fontStretch: 'inherit',
    lineHeight: 'inherit',
    letterSpacing: 'inherit',
  },
  hero: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '40px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  title: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '26px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  subtitle: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '20px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  subtitle2: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '16px',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  sectionHeader: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '16px',
    fontWeight: '600',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  navigation: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '15px',
    fontWeight: '600',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  paragraph: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '14px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.57',
    letterSpacing: 'normal',
  },
  label: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '14px',
    fontWeight: 600,
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.57',
    letterSpacing: 'normal',
  },
  data: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '12px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.17',
    letterSpacing: 'normal',
  },
  caption: {
    fontFamily: 'Work Sans, sans-serif',
    fontSize: '11px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: '1.27',
    letterSpacing: 'normal',
  },
};
