query PROGRAM_DONOR_INDEX_STATS($programShortName: String!) {
  programDonorSummary(programShortName: $programShortName) {
    stats {
      programShortName
      lastUpdate
      allFilesCount
      registeredDonorsCount
    }
  }
}
