query STATS($filters: JSON) {
  file {
    hits(filters: $filters) {
      total
    }
    aggregations(filters: $filters, include_missing: true, aggregations_filter_themselves: true) {
      donors__donor_id {
        bucket_count
      }
      study_id {
        bucket_count
      }
      file__size {
        stats {
          sum
        }
      }
    }
  }
}
