query STATS($filters: JSON) {
  file {
    hits(filters: $filters) {
      total
    }
    aggregations(filters: $filters, include_missing: true) {
      donors__donor_id {
        buckets {
          key
        }
      }
      study_id {
        buckets {
          key
        }
      }
      file__size {
        stats {
          sum
        }
      }
    }
  }
}
