export enum FileCentricDocumentField {
  object_id = 'object_id',
  'donors.donor_id' = 'donors.donor_id',
  study_id = 'study_id',
  data_type = 'data_type',
  file_type = 'file_type',
  'analysis.experiment.experimental_strategy' = 'analysis.experiment.experimental_strategy',
  'file.size' = 'file.size',
  'donors.gender' = 'donors.gender',
  'analysis.variant_class' = 'analysis.variant_class',
  file_access = 'file_access',
  data_category = 'data_category',
  analysis_tools = 'analysis_tools',
  'donors.specimens.specimen_type' = 'donors.specimens.specimen_type',
  'donors.specimens.specimen_tissue_source' = 'donors.specimens.specimen_tissue_source',
  'analysis.workflow.workflow_name' = 'analysis.workflow.workflow_name',
}
