query DATA_TYPE_CHART($filters: JSON) {
  file {
    aggregations(filters: $filters, include_missing: true) {
      program_ids: study_id {
        buckets {
          doc_count
          key
        }
      }
    }
  }
}
