query CLINICAL_SUBMISSION_DATA($programShortName: String!) {
  clinicalData(programShortName: $programShortName) {
    programShortName
    clinicalEntities {
      entityName
      records {
        row
        fields {
          name
          value
        }
      }
    }
  }
}
