query CLINICAL_SUBMISSION_DATA($programShortName: String!) {
  clinicalData(programShortName: $programShortName) {
    programShortName
    clinicalEntities {
      entityName
      entityFields
      records {
        name
        value
      }
    }
  }
}
