query CLINICAL_ENTITY_DATA($programShortName: String!) {
  clinicalData(programShortName: $programShortName) {
    programShortName
    clinicalEntities {
      entityName
      entityFields
      records {
        name
        value
      }
    }
    schemaMetadata {
      lastValidSchemaVersion
      originalSchemaVersion
      isValid
      lastMigrationId
    }
    completionStats {
      coreCompletion {
        donor
        specimens
        primaryDiagnosis
        followUps
        treatments
      }
      coreCompletionDate
      coreCompletionPercentage
      overriddenCoreCompletion
    }
  }
}
