query CLINICAL_SUBMISSION_DATA($programShortName: String!) {
  clinicalSubmissions(programShortName: $programShortName) {
    programShortName
    state
    clinicalEntities {
      clinicalType
      records {
        row
        fields {
          name
          value
        }
      }
      stats {
        noUpdate
        new
        updated
        errorsFound
      }
      dataErrors {
        type
        message
        row
        field
        value
        donorId
      }
      schemaErrors {
        type
        message
        row
        field
        value
        donorId
        clinicalType
      }
    }
  }
}
