query CLINICAL_ENTITY_DATA(
  $programShortName: String!
  $first: Int!
  $offset: Int!
  $filters: QueryFilter
  $sort: [QuerySort]
) {
  clinicalData(
    variables: {
      programShortName: $programShortName
      first: $first
      offset: $offset
      filters: $filters
      sort: $sort
    }
  ) {
    clinicalEntities {
      entityName
      entityFields
      records {
        name
        value
      }
    }
    completionStats {
      coreCompletion {
        donor
        specimens
        primaryDiagnosis
        familyHistory
        followUps
        treatments
      }
      coreCompletionDate
      coreCompletionPercentage
      overriddenCoreCompletion
      donorId
    }
  }
}
