query CLINICAL_ENTITY_DATA($programShortName: String!) {
  clinicalData(programShortName: $programShortName) {
    clinicalEntities {
      entityName
      entityFields
      records {
        name
        value
      }
    }
    completionStats {
      coreCompletion {
        donor
        specimens
        primaryDiagnosis
        familyHistory
        followUps
        treatments
      }
      coreCompletionDate
      coreCompletionPercentage
      overriddenCoreCompletion
      donorId
    }
  }
}
