query SIDE_MENU_SAMPLE_REGISTRATION_STATE($programShortName: String!) {
  clinicalRegistration(shortName: $programShortName) {
    programShortName
    fileErrors {
      message
      code
    }
    fileName
    errors {
      type
    }
  }
}
