query SIDE_MENU_CLINICAL_SUBMISSION_STATE($programShortName: String!) {
  clinicalSubmissions(programShortName: $programShortName) {
    programShortName
    state
    clinicalEntities {
      schemaErrors {
        row
      }
    }
  }
}
