export const mockPrograms = [
  {
    id: null,
    shortName: 'RB_Test',
    name: 'RB_Test',
    cancerTypes: [],
    countries: 'CA',
    membershipType: 'ASSOCIATE',
    genomicDonors: 100,
    submittedDonors: 5,
    commitmentDonors: 1000,
  },
  {
    id: null,
    shortName: 'WPCPMP1',
    name: 'Weill Corneil Cancer Precision Medecine Program 3',
    cancerTypes: [],
    countries: 'USA',
    membershipType: 'FULL',
    genomicDonors: 0,
    submittedDonors: 0,
    commitmentDonors: 3000,
  },
  {
    id: null,
    shortName: 'June5TestRB_CancerTypes2',
    name: 'June5TestRB_CancerTypes2',
    cancerTypes: [
      { id: 'cancer_1', name: 'Breast Cancer' },
      { id: 'cancer_2', name: 'Cervical Cancer' },
      { id: 'cancer_3', name: 'Pancreatic Cancer' },
    ],
    countries: 'hi',
    membershipType: 'FULL',
    genomicDonors: 50000,
    submittedDonors: 50000,
    commitmentDonors: 50000,
  },
  {
    id: null,
    shortName: 'WPCPMP',
    name: 'Weill Corneil Cancer Precision Medecine Program 2',
    cancerTypes: [],
    countries: 'USA',
    membershipType: 'FULL',
    genomicDonors: 0,
    submittedDonors: 0,
    commitmentDonors: 3000,
  },
  {
    id: null,
    shortName: 'June5TestRB',
    name: 'June5TestRB',
    cancerTypes: [],
    countries: 'Hello',
    membershipType: 'FULL',
    genomicDonors: 10,
    submittedDonors: 10,
    commitmentDonors: 10,
  },
  {
    id: null,
    shortName: 'PACA-AU',
    name: 'Australian Pancreatic Cancer Program',
    cancerTypes: [],
    countries: 'Australia',
    membershipType: 'FULL',
    genomicDonors: 0,
    submittedDonors: 0,
    commitmentDonors: 2000,
  },
  {
    id: null,
    shortName: 'Jon Test Program 1',
    name: 'JON-CA-1',
    cancerTypes: [],
    countries: 'CA',
    membershipType: 'FULL',
    genomicDonors: 1,
    submittedDonors: 1,
    commitmentDonors: 1,
  },
  {
    id: null,
    shortName: 'WP-CPMP',
    name: 'Weill Corneil Cancer Precision Medecine Program',
    cancerTypes: [],
    countries: 'USA',
    membershipType: 'FULL',
    genomicDonors: 0,
    submittedDonors: 0,
    commitmentDonors: 3000,
  },
  {
    id: null,
    shortName: 'd603',
    name: 'demo603',
    cancerTypes: [],
    countries: null,
    membershipType: 'FULL',
    genomicDonors: 1,
    submittedDonors: 1,
    commitmentDonors: 1,
  },
  {
    id: null,
    shortName: 'RB_Test2',
    name: 'RB_Test2',
    cancerTypes: [],
    countries: 'CA',
    membershipType: 'FULL',
    genomicDonors: 100,
    submittedDonors: 5,
    commitmentDonors: 1000,
  },
  {
    id: null,
    shortName: 'June5TestRB_CancerTypes',
    name: 'June5TestRB_CancerTypes',
    cancerTypes: [],
    countries: 'Hello',
    membershipType: 'FULL',
    genomicDonors: 10,
    submittedDonors: 10,
    commitmentDonors: 10,
  },
  {
    id: null,
    shortName: 'Member type test',
    name: 'Member type tes',
    cancerTypes: [],
    countries: 'Member type tes',
    membershipType: 'FULL',
    genomicDonors: 10,
    submittedDonors: 10,
    commitmentDonors: 10,
  },
  {
    id: null,
    shortName: 'Hello1',
    name: 'Hello1',
    cancerTypes: [],
    countries: 'Hello',
    membershipType: 'FULL',
    genomicDonors: 10,
    submittedDonors: 10,
    commitmentDonors: 10,
  },
  {
    id: null,
    shortName: 'Magical',
    name: 'Hello',
    cancerTypes: [],
    countries: 'Hello',
    membershipType: 'FULL',
    genomicDonors: 10,
    submittedDonors: 10,
    commitmentDonors: 10,
  },
  {
    id: null,
    shortName: 'Test - Ego NULL',
    name: 'Testing',
    cancerTypes: [],
    countries: 'Hello',
    membershipType: 'ASSOCIATE',
    genomicDonors: 10,
    submittedDonors: 10,
    commitmentDonors: 10,
  },
];
