fragment Registration on ClinicalRegistrationData {
  id
  programShortName
  creator
  fileName
  createdAt
  records {
    row
    fields {
      name
      value
    }
  }
  errors {
    type
    message
    row
    field
    value
    sampleId
    donorId
    specimenId
  }
  fileErrors {
    message
    code
  }
  newDonors {
    count
    rows
  }
  newSpecimens {
    count
    rows
  }
  newSamples {
    count
    rows
  }
  alreadyRegistered {
    count
    rows
  }
}
