mutation UPLOAD_REGISTRATION($shortName: String!, $registrationFile: Upload!) {
  uploadClinicalRegistration(shortName: $shortName, registrationFile: $registrationFile) {
    ... on ClinicalRegistrationData {
      id
    }

    ... on ClinicalRegistrationInvalid {
      error
      code
    }
  }
}
