query PROGRAM_QUERY($shortName: String!) {
  program(shortName: $shortName) {
    name
    shortName
    description
    commitmentDonors
    submittedDonors
    genomicDonors
    website
    institutions
    countries
    regions
    membershipType
    cancerTypes
    primarySites
  }
}
