// flow-typed signature: 0d46adbf202ba7ceb80f83e8e26782e3
// flow-typed version: <<STUB>>/apollo-cache-inmemory_v1.6.2/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-cache-inmemory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-cache-inmemory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-cache-inmemory/jest.config' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/__tests__/cache' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/__tests__/diffAgainstStore' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/__tests__/fragmentMatcher' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/__tests__/mapCache' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/__tests__/objectCache' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/__tests__/readFromStore' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/__tests__/recordingCache' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/__tests__/roundtrip' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/__tests__/writeToStore' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/bundle.cjs' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/bundle.cjs.min' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/bundle.esm' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/depTrackingCache' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/fixPolyfills' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/fragmentMatcher' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/fragmentMatcherIntrospectionQuery' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/inMemoryCache' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/mapCache' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/objectCache' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/readFromStore' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/types' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/writeToStore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-cache-inmemory/jest.config.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/jest.config'>;
}
declare module 'apollo-cache-inmemory/lib/__tests__/cache.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/__tests__/cache'>;
}
declare module 'apollo-cache-inmemory/lib/__tests__/diffAgainstStore.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/__tests__/diffAgainstStore'>;
}
declare module 'apollo-cache-inmemory/lib/__tests__/fragmentMatcher.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/__tests__/fragmentMatcher'>;
}
declare module 'apollo-cache-inmemory/lib/__tests__/mapCache.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/__tests__/mapCache'>;
}
declare module 'apollo-cache-inmemory/lib/__tests__/objectCache.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/__tests__/objectCache'>;
}
declare module 'apollo-cache-inmemory/lib/__tests__/readFromStore.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/__tests__/readFromStore'>;
}
declare module 'apollo-cache-inmemory/lib/__tests__/recordingCache.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/__tests__/recordingCache'>;
}
declare module 'apollo-cache-inmemory/lib/__tests__/roundtrip.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/__tests__/roundtrip'>;
}
declare module 'apollo-cache-inmemory/lib/__tests__/writeToStore.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/__tests__/writeToStore'>;
}
declare module 'apollo-cache-inmemory/lib/bundle.cjs.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/bundle.cjs'>;
}
declare module 'apollo-cache-inmemory/lib/bundle.cjs.min.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/bundle.cjs.min'>;
}
declare module 'apollo-cache-inmemory/lib/bundle.esm.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/bundle.esm'>;
}
declare module 'apollo-cache-inmemory/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/bundle.umd'>;
}
declare module 'apollo-cache-inmemory/lib/depTrackingCache.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/depTrackingCache'>;
}
declare module 'apollo-cache-inmemory/lib/fixPolyfills.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/fixPolyfills'>;
}
declare module 'apollo-cache-inmemory/lib/fragmentMatcher.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/fragmentMatcher'>;
}
declare module 'apollo-cache-inmemory/lib/fragmentMatcherIntrospectionQuery.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/fragmentMatcherIntrospectionQuery'>;
}
declare module 'apollo-cache-inmemory/lib/index.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/index'>;
}
declare module 'apollo-cache-inmemory/lib/inMemoryCache.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/inMemoryCache'>;
}
declare module 'apollo-cache-inmemory/lib/mapCache.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/mapCache'>;
}
declare module 'apollo-cache-inmemory/lib/objectCache.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/objectCache'>;
}
declare module 'apollo-cache-inmemory/lib/readFromStore.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/readFromStore'>;
}
declare module 'apollo-cache-inmemory/lib/types.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/types'>;
}
declare module 'apollo-cache-inmemory/lib/writeToStore.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/writeToStore'>;
}
