// flow-typed signature: 89506987c11b6abcfc78fb29fe001016
// flow-typed version: <<STUB>>/graphql-import_v^0.7.1/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "graphql-import" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "graphql-import/dist/definition" {
  declare module.exports: any;
}

declare module "graphql-import/dist/index" {
  declare module.exports: any;
}

declare module "graphql-import/dist/index.test" {
  declare module.exports: any;
}

// Filename aliases
declare module "graphql-import/dist/definition.js" {
  declare module.exports: $Exports<"graphql-import/dist/definition">;
}
declare module "graphql-import/dist/index.js" {
  declare module.exports: $Exports<"graphql-import/dist/index">;
}
declare module "graphql-import/dist/index.test.js" {
  declare module.exports: $Exports<"graphql-import/dist/index.test">;
}
