// flow-typed signature: d1350fa4692b3d8b5dd0eb5f4b50ee14
// flow-typed version: <<STUB>>/next-cookies_v^1.1.2/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "next-cookies" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "next-cookies/dist/next-cookies.browser" {
  declare module.exports: any;
}

declare module "next-cookies/next-cookies.node" {
  declare module.exports: any;
}

// Filename aliases
declare module "next-cookies/dist/next-cookies.browser.js" {
  declare module.exports: $Exports<"next-cookies/dist/next-cookies.browser">;
}
declare module "next-cookies/next-cookies.node.js" {
  declare module.exports: $Exports<"next-cookies/next-cookies.node">;
}
