// flow-typed signature: aa480db08d59d63ade30cc799fd28291
// flow-typed version: <<STUB>>/react-apollo-hooks_v0.4.5/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-apollo-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-apollo-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-apollo-hooks/es/ApolloContext' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/es/getMarkupFromTree' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/es/index' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/es/internal/__mocks__/actHack' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/es/internal/actHack' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/es/internal/SSRContext' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/es/queryCache' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/es/SuspenseSSR' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/es/useMutation' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/es/useQuery' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/es/useSubscription' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/es/utils' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/ApolloContext' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/getMarkupFromTree' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/index' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/internal/__mocks__/actHack' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/internal/actHack' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/internal/SSRContext' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/queryCache' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/SuspenseSSR' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/useMutation' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/useQuery' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/useSubscription' {
  declare module.exports: any;
}

declare module 'react-apollo-hooks/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-apollo-hooks/es/ApolloContext.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/ApolloContext'>;
}
declare module 'react-apollo-hooks/es/getMarkupFromTree.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/getMarkupFromTree'>;
}
declare module 'react-apollo-hooks/es/index.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/index'>;
}
declare module 'react-apollo-hooks/es/internal/__mocks__/actHack.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/internal/__mocks__/actHack'>;
}
declare module 'react-apollo-hooks/es/internal/actHack.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/internal/actHack'>;
}
declare module 'react-apollo-hooks/es/internal/SSRContext.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/internal/SSRContext'>;
}
declare module 'react-apollo-hooks/es/queryCache.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/queryCache'>;
}
declare module 'react-apollo-hooks/es/SuspenseSSR.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/SuspenseSSR'>;
}
declare module 'react-apollo-hooks/es/useMutation.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/useMutation'>;
}
declare module 'react-apollo-hooks/es/useQuery.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/useQuery'>;
}
declare module 'react-apollo-hooks/es/useSubscription.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/useSubscription'>;
}
declare module 'react-apollo-hooks/es/utils.js' {
  declare module.exports: $Exports<'react-apollo-hooks/es/utils'>;
}
declare module 'react-apollo-hooks/lib/ApolloContext.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/ApolloContext'>;
}
declare module 'react-apollo-hooks/lib/getMarkupFromTree.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/getMarkupFromTree'>;
}
declare module 'react-apollo-hooks/lib/index.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/index'>;
}
declare module 'react-apollo-hooks/lib/internal/__mocks__/actHack.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/internal/__mocks__/actHack'>;
}
declare module 'react-apollo-hooks/lib/internal/actHack.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/internal/actHack'>;
}
declare module 'react-apollo-hooks/lib/internal/SSRContext.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/internal/SSRContext'>;
}
declare module 'react-apollo-hooks/lib/queryCache.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/queryCache'>;
}
declare module 'react-apollo-hooks/lib/SuspenseSSR.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/SuspenseSSR'>;
}
declare module 'react-apollo-hooks/lib/useMutation.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/useMutation'>;
}
declare module 'react-apollo-hooks/lib/useQuery.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/useQuery'>;
}
declare module 'react-apollo-hooks/lib/useSubscription.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/useSubscription'>;
}
declare module 'react-apollo-hooks/lib/utils.js' {
  declare module.exports: $Exports<'react-apollo-hooks/lib/utils'>;
}
