query GET_JOIN_PROGRAM_INFO($inviteId: ID!) {
  joinProgramInvite(id: $inviteId) {
    program {
      name
      shortName
    }
    user {
      role
      email
      firstName
      lastName
    }
    status
  }
  programOptions {
    institutions
  }
}
