mutation CREATE_PROGRAM_MUTATION($program: ProgramInput!) {
  createProgram(program: $program) {
    description
    name
    commitmentDonors
    submittedDonors
    genomicDonors
    website
    institutions
    countries
    regions
    membershipType
  }
}

mutation UPDATE_PROGRAM_MUTATION($updates: UpdateProgramInput!, $shortName: String!) {
  updateProgram(shortName: $shortName, updates: $updates)
}
