query PROGRAM_DONOR_SUMMARY_QUERY(
  $programShortName: String!
  $first: Int!
  $offset: Int!
  $sorts: [DonorSummaryEntrySort]
) {
  programDonorSummaryEntries(
    programShortName: $programShortName
    first: $first
    offset: $offset
    sorts: $sorts
  ) {
    id
    donorId
    programShortName
    validWithCurrentDictionary
    releaseStatus
    submitterDonorId
    submittedCoreDataPercent
    submittedExtendedDataPercent
    registeredNormalSamples
    registeredTumourSamples
    publishedNormalAnalysis
    publishedTumourAnalysis
    alignmentsCompleted
    alignmentsRunning
    alignmentsFailed
    sangerVcsCompleted
    sangerVcsRunning
    sangerVcsFailed
    processingStatus
    updatedAt
  }
  programDonorSummaryStats(programShortName: $programShortName) {
    registeredDonorsCount
    fullyReleasedDonorsCount
    partiallyReleasedDonorsCount
    noReleaseDonorsCount
    donorsInvalidWithCurrentDictionaryCount
  }
}
