#import "./CLINICAL_SUBMISSION_FRAGMENT.gql"

mutation CLEAR_SUBMISSION_MUTATION(
  $programShortName: String!
  $submissionVersion: String!
  $fileType: String
) {
  clearClinicalSubmission(
    programShortName: $programShortName
    version: $submissionVersion
    fileType: $fileType
  ) {
    ...ClinicalSubmissionFragment
  }
}
