#import "./CLINICAL_SUBMISSION_FRAGMENT.gql"

query CLINICAL_SUBMISSIONS_QUERY($programShortName: String!) {
  program(shortName: $programShortName) {
    name
  }
  clinicalSubmissions(programShortName: $programShortName) {
    ...ClinicalSubmissionFragment
  }
}
