fragment ClinicalSubmissionFragment on ClinicalSubmissionData {
  programShortName # this is the ID
  state
  version
  clinicalEntities {
    clinicalType
    batchName
    creator
    createdAt
    stats {
      noUpdate
      new
      updated
      errorsFound
    }
    records {
      row
      fields {
        name
        value
      }
    }
    dataUpdates {
      row
      field
      newValue
      oldValue
      donorId
    }
    dataErrors {
      message
      row
      field
      value
      donorId
    }
    schemaErrors {
      message
      row
      field
      value
      donorId
    }
  }
  fileErrors {
    msg
    fileNames
    code
  }
}
