#import "./CLINICAL_SUBMISSION_FRAGMENT.gql"

mutation UPLOAD_CLINICAL_SUBMISSION($programShortName: String!, $files: [Upload!]) {
  clinicalSubmissions: uploadClinicalSubmissions(
    programShortName: $programShortName
    clinicalFiles: $files
  ) {
    ...ClinicalSubmissionFragment
  }
}
